---
- name: Configure Apache Web Server
  hosts: webserver
  become: true

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache
      systemd:
        name: httpd
        state: started
        enabled: true

    - name: Copy and extract HTML, CSS, JS files
      unarchive:
        src: files/2131_wedding_lite.tar.gz
        dest: /var/www/html/
        remote_src: false
        owner: apache
        group: apache
        mode: '0755'
