---
- name: Configure Apache to serve HTTPS
  hosts: webserver
  become: true

  tasks:
    - name: Install SSL Dependencies
      yum:
        name: mod_ssl
        state: present

    - name: Create the /etc/ssl/private directory
      file:
        path: /etc/ssl/private
        state: directory
        mode: '0700'

    - name: Generate private key
      command: openssl genrsa -out /etc/ssl/private/apache-selfsigned.key 2048 creates=etc/ssl/private/apache-selfsigned.key

    - name: Generate CSR 
      command: openssl req -new -key /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.csr -subj "/CN={{ ansible_default_ipv4.address }}"

    - name: Generate self signed certificate
      command: openssl x509 -req -days 365 -in /etc/ssl/certs/apache-selfsigned.csr -signkey /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt creates=/etc/ssl/certs/apache-selfsigned.crt

    - name: Ensure SSL certificate path is set to the self-signed certificate
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regex: '^SSLCertificateFile'
        line: 'SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt'

    - name: Ensure SSL key path is set to the self-signed key
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regex: '^SSLCertificateKeyFile'
        line: 'SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key'

    - name: Restart Apache
      systemd:
        name: httpd
        state: restarted
        